### ISSUE TITLE
Where I can find smali and  baksmali *.jar?

### ISSUE THREAD

**Issue by t2hv33** [JesusFreke/smali#302]
Where I can find smali and  baksmali *.jar?
I can not build jar from this source code.
Can anyone give me link download this file.
Thank you guys so much.

**Comment by CalebFenton** [comment]
Releases are here: https://github.com/JesusFreke/smali/releases (no compiling neeeded)

Build instructions here: https://github.com/JesusFreke/smali/wiki/BuildProcedure

**Comment by JesusFreke** [comment]
@CalebFenton those are just source jars that are automatically generated by github.

Releases are currently at https://bitbucket.org/JesusFreke/smali/downloads  (I guess I should put that on the main github page :))

When googlecode's downloads were deprecated, I chose not to use github due to a lack of download count or anything. But it looks like they offer an api to get this information now, so I'll likely transition to using github releases. And then I can delete the bitbucket project and everything will be on github \o/
