### ISSUE TITLE
add type information for const and const-wide instructions

### ISSUE THREAD

**Issue by ghost** [JesusFreke/smali#305]
Hi,

I notice that smali code doesn't contain the type information about the const and const-wide instructions. Then it's not that clear what type of variables are transmitted to this virtual register. For example, const/high16 could be a float or other types. 

Can anyone guide me how to add the type information for const and const-wide instructions? For example, "const/4 v0, 0x0" can be changed to "const/4 v0, 0x0 #int"?

Best regards,

Xiangyang

**Comment by Fuzion24** [comment]
Debug symbol type confusion sounds like a fun thing to add to obfuscators :D

**Comment by CalebFenton** [comment]
@Fuzion24 :+1: evil genius points

**Comment by XiangyangGuo** [comment]
Thanks for your reply. @CalebFenton  and @Fuzion24 

For some reason, I need to add the type information to the 'const' and 'const-wide' instructions. (probably at the end of the same line as a  # comment like this # int or # long ). For example, if the source code is "return false" for a function whose return type is boolean. The smali code could be "const/4 v0, 0x0" and "return v0". In this case, I don't know the return type is a 'boolean' without checking the function ifself. Another example, if the source code is "int a = b & 0xFF00", then the smali code for '0xFF00'  could be 'const/high16 v0, 0xff00', then I don't know what type of this 'v0' because const/high16 can be some other types. So the best thing for me is to change the source code of smali so that it can add type information for each 'const' or 'const-wide' instructions.

I appreciate it if you can tell me how to modify the source code of smali/baksmali to add the type information instead of getting the clue from the context.

Thanks,

Xiangyang

**Comment by CalebFenton** [comment]
Sorry. Compilation is lossy. Primitive type information *must* be reconstructed from context. Why do you need it?

**Comment by JesusFreke** [comment]
baksmali can't add the type information without doing significant static analysis first. There is some existing register-based type analysis already (see the -r option for baksmali), but this analysis is primarily for deodexing, and it doesn't propagate type information backwards from where a register is used, but only forward.

**Comment by XiangyangGuo** [comment]
I see. I need this type info because I want to feed the smali code to my tool (which needs type info) to run it.

After a quick check, it seems that Google's 'dexdump' can dump the 'const'  and 'const-wide' instrucitons with type information attached. Probably I need to combine the 'smali' and 'dexdump' together to get my tool work.

BTW, I think it should be interesting to add this information into smali. And thank you for your reply.

**Comment by JesusFreke** [comment]
I don't think dexdump will give you the information you're looking for either. e.g.

https://gist.github.com/JesusFreke/b2bac66760feed7accf1

There are 2 const-wide instructions, one is later used as a long, the other is later used as a double, but dexdump shows double for both

**Comment by XiangyangGuo** [comment]
You are right, @JesusFreke . It seems dexdump cannot always dump the right type information.

So I think I need (1) use the debug symbols ".local v18, "i":J" for variable 'i' in this case "long i = 1234567;" (2) use context for "0xff" in this case "l = l & 0xff; ".  For example, with the following two smali instructions "const-wide/16 v26, 0xff" and "and-long v24, v24, v26 ", I can figure out the v26 is 'long'.

Does this sound doable?  Thanks

**Comment by CalebFenton** [comment]
Be careful relying on debug information. It's sometimes stripped, usually with proguard. And as @Fuzion24 pointed out, it can be spoofed.

**Comment by JesusFreke** [comment]
You can't rely on debug information. And even when using context as you mentioned, you may not be able to determine a single type for the value. For instance:

https://pastee.org/4w869

The wide value in v0, v1 is used as both a long and a double.

**Comment by CalebFenton** [comment]
Good point. Type reconstruction is messy.

**Comment by XiangyangGuo** [comment]
@JesusFreke , Thanks for pointing it out. However, I was wondering what kind of source code can generate that smali code?  I assume it looks like         
{
    System.out.println(Long.toString(0x1234));
    System.out.println(Double.toString(0x1234));
}

However, it give me different smali code as yours. It defines 0x1234 twice and one is for long and another is for double.

**Comment by JesusFreke** [comment]
You can do many things in bytecode that can't be directly expressed in a given JVM language.
