### ISSUE TITLE
Decompile - compile of Sailfish OS dalvik framework results corrupt file

### ISSUE THREAD

**Issue by vermut** [JesusFreke/smali#375]
I downloaded whole /opt/aliens/system directory
Then in ./system/framework I ran
`java -jar ~/Downloads/baksmali-2.1.1.jar -x framework.odex -d .`
`java -jar ~/Downloads/smali-2.1.1.jar out -o framework2.odex`

A. They differ in size:
```
-rw-rw-r-- 1 root root 9210072 Nov 13 06:09 framework.odex
-rw-r--r-- 1 root root 8419872 Mar 12 00:34 framework2.odex
```
B. And when I uploaded recompiled framework back it crashed:
`unhandled page fault (11) at 0xdeadbaad, code 0x80d`

Where can I look for clues?

[framework_and_core.zip](https://github.com/JesusFreke/smali/files/170113/framework_and_core.zip)

**Comment by JesusFreke** [comment]
Yes, small size differences are expected.

Smali produces a dex file, not an odex file. You can't just load a dex file as an odex file :). You need to either put it back in the framework.jar as classes.dex, or run dexopt on the device to generate the correct odex file.

It's worth pointing out that when you change any of the framework jars (e.g. by deodexing them), it invalidates all odexes on the devices, so you have to deodex everything on the system image.

**Comment by vermut** [comment]
Well well, how illiterate I am. I understand I have to go and read the manuals, but maybe you can quickly answer few questions so I can understand the scale of trouble I'm in.

1. The correct cycle is backsmali framework.odex -> smali 'out' -> 'zip -r framework.jar classes.dex' ?
2. Even if I run the cycle above it invalidates everything and I need to run it for every .odex file in /system/ ?
3. I also have .odex files in /app/ - they are doomed too?

**Comment by JesusFreke** [comment]
1. Yes
2. Yes
3. In /system/app and /system/priv-app, Yes

**Comment by vermut** [comment]
Well, thank you for the pointers. Odex, here I come.

**Comment by vermut** [comment]
(Last one, I hope)

Even if I deodexed all files, created classes.dex and moved them to respective jars/apks - it won't work? I must create new .odex files somehow? 

And copy signature like [described here](http://home.scarlet.be/~rh323092/deodex.html) ? Or it's only when I need to patch single file?

[Deodexing script I used](https://gist.github.com/vermut/140c3eb6e019429c7f45)

**Comment by JesusFreke** [comment]
Yes, you can create new odex files if you want, or you can stick the classes.dex file back in the framework jars/app apks.

Since apks are signed, you might expect this to cause problems. However, last I checked (not sure if this is still true, TBH), android doesn't fully verify the signature of system apks. In particular, it's possible to add a new file to the apk that isn't listed in the MANIFEST.MF file. And classes.dex typically isn't listed - so you can insert classes.dex into the apk without invalidating the signatures.

Copying the odex signature is a hack to avoid having to deodex the entire system image. This is dangerous if you don't know exactly what you're doing. It should work if you don't make any changes to the deodexed dex files. But as soon as you make changes, it can cause crashes, etc.

**Comment by vermut** [comment]
Solved with [Universal Deodexer V5](http://forum.xda-developers.com/showthread.php?t=2213235) which is essentially a smart wrapper around smali.

**Comment by nomeata** [comment]
Are there alternatives to the Universal Deodexer that work on Linux?
