### ISSUE TITLE
[RFE] SingletonMultiDexContainer

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#446]
in current uses of SingletonMultiDexContainer, getDexEntryNames() should return a `List<String>` containing `{ SingletonMultiDexContainer.NO_NAME }`, where NO_NAME is a specific instance of `""`.

clients can then check for object identity with `(getDexEntryNames().get(0)) == SingletonMultiDexContainer.NO_NAME` to determine that the entry in the dex file container is actually unamed.

> NOTE: i'd much rather prefer a list containing null instead. the problem is that you declared @Nonnull in `getEntry(@Nonnull String entryName)`. 

why the NO_NAME constant? if you want to process a subset of dex files (for example, the "classes[0-9]*.dex" in the root directory of the container) then you have to filter the container contents. UNLESS... the contents don't have a name, as in the case of naked dex and odex files (the only users of SingletonMultiDexContainer for now).

returning the name of the outer file, as happens now, is useless and can only confuse things. the reality is that some containers are singletons without an inner name.

the workaround would be to test SingletonMultiDexContainer (ugly), only it can't be done because the class is private. so the real workaround is to avoid using DexFileFactory.loadDexContainer completely, which is what i'm doing now. (BTW, not such a big loss because loadDexContainer can't handle directories as dex containers, which is something i desire in my tool.)

and finally, i'd suggest making "SingletonMultiDexContainer<? extends DexFile>" public, since it can be useful for some clients.

**Comment by JesusFreke** [comment]
Hmm. I think I'll have to disagree on this one.  Conceptually speaking the dex file *does* have a name - it's name on the filesystem. NO_NAME would make sense if, e.g. the dex file only existed in memory or something.

The "loadDexContainer" method is meant for use when you know the file is most likely not a single dex file. (i.e. the "list dex" command in baksmali). The SingletonMultiDexContainer is meant as a mostly-sane fallback in case the user passes in a dex file for some reason.

It sounds like your use cases are complicated enough (and at odds enough with dexlib2's intentional dex-centricity) to warrant writing your own "DexFileFactory" type of logic. e.g. If you want to extend ZipDexContainer anyway, that will preclude the use of the existing DFF.loadDexContainer.

**Comment by Lanchon** [comment]
well no biggie, i am writing my own factory anyway. and for now i'm only filtering if instanceof zip container. thanks!
