### ISSUE TITLE
autodetecting 'Opcodes'

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#459]
hi JF,

it seems there is no way to autodetect the api level/art version when reading a dex binary in dexlib2. is there a reason why this is so? are you working on this? or would you be interested in a pull request?

btw, i'm writing multi-dex files in multi-threaded mode, and i'm NOT impressed by the results at all... :(
https://github.com/DexPatcher/dexpatcher-tool/releases

**Comment by JesusFreke** [comment]
Not sure what you mean. oat files automatically use the correct Opcodes based on the oat version. But dex/odex files don't store any information about the api level, so there's no good way to do autodetection in that case, unless you want to try to guess based on the bytecode.

It would be interesting to compare the performance of writing out a dex file with dexlib2 with the performance of that step in dx. It's been a while since I've looked at the performance of writing out a dex file, but from what I do recall, there's only so much that can be done to speed it up. It boils down to the fact that there are a lot of hash calculations and comparisons needed in order to intern all the various types of items in their respective pools.

**Comment by Lanchon** [comment]
well i'm no expert but i'm under the assumption that the dex file format version determines the opcodes that are valid and their meaning, just like the java bytecode version does.

this means that a VM just needs to know the dex version to load and execute the dex.

of course the code in the dex typically has dependencies on the rest of the runtime (starting with the java.lang package), and that is what the api level specifies. but the VM itself shouldn't need to know the api level to run code: it should just need the dex file (with the self-contained version info) and the boot classpath. the client of the VM starts it with the right classpaths.

in a similar way, tools that don't care about the runtime shouldn't need to know the api level and should be able to work just with the info within the dex file. my tool is one such tool: it will not create dependencies on the runtime that were not already present on the input files.

that is my assumption anyway, but i could be wrong.

but if i'm right, then it should be possible to create an Opcodes instance from the dex file version, and this is what i'm proposing here.

while on the subject, i don't know why you need the api level to baksmali. under these assumptions, you should be able to create a textual dump of a dex file that expreses the complete meaning of it without knowing the api level. (and of course without these assumptions you should be able to dump too, but the meaning of the dump would not be completely defined.)

**Comment by JesusFreke** [comment]
The publicly documented and officially supported opcodes are tied to the dex file version. But the non-documented and not officially supported optimized opcodes that are intended for use in odex files are not tied to any particular odex/dex version. Ideally, this wouldn't be a problem for normal dex files, because they shouldn't contain these opcodes, right? .... right?

I wish :)

Unfortunately, dalvik (and possibly art?) allows a subset of these optimized opcodes to occur within a normal unoptimized dex file. But these opcodes have changed over time which is why we need the api level and differing sets of opcodes based on that api level.

**Comment by Lanchon** [comment]
thanks so much for the explanation.

so i was looking at the versioning code. according to VersionMap, there is a one-to-many relationship between art ver and api level. (not many-to-many: art completely determines api.)

[mapApiToArtVersion] (https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/VersionMap.java#L59-L73) returns the lowest art in range for a given api. it could be called mapApiToMinArtVersion instead.

[here] (https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/Opcodes.java#L81), when you initialize Opcodes for an api (not for art ver), and the api is lollipop or later (ie, system has art), then you also include the art opcodes corresponding to the art ver corresponding to the api level.

presumably this is done because of what you explain here: some dex files use undocumented oat opcodes. (or maybe when loading oats via the command line baksmali you specify api; IDK, i don't use baksmali.)

in any case, i think there is a small issue.

api 22 corresponds to art vers 45 through 63 inclusive. say you construct an Opcodes for api 22; it has art opcodes too, those of version 45.

wouldn't it be better to construct the Opcodes for art version 63 instead? within an api level, it's a good bet that art opcodes might more probably be added rather than changed or deleted. wouldn't it be better to use mapApiToMaxArtVersion instead of mapApiToMinArtVersion in this context?

---------------

but what is really needed for api 22 is an Opcodes instance that does not correspond to any particular art version, but is a superset of all comprehended art versions. and in this case this is impossible to achieve since the same 0x73 opcode is used for different instructions in different art versions.

so one must ask: what is the usefulness of mapApiToMin/MaxArtVersion and constructing art opcodes based on an api level at all? what client uses this, and should the client be restructured to avoid it?

----------------

anyway... i saw that documented dex opcodes don't have this problem: they are only added with time. so a dex file for an api level is always valid and means the same under a higher api level.

so i can achieve my goal of better default Opcodes by reading the dex header and calling a hypothetical mapDexVersionToMaxApi (or mapDexVersionToMaxArtVersion), then creating Opcodes from the result.

mapDexVersionToMaxApi is very easy to implement: just two valid values in, 35 and 37 (api level is 26 for 37).

the problem is that i think this helper belongs in dexlib, not my code. when dexlib is updated to support a new api level or a new dex format, we shouldn't really need to change client code to accommodate that.

so could you maybe consider these to to VersionMap?
- mapApiToDexVersion
- mapDexVersionToMaxApi

you would then use those to implement this:
https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/dexbacked/raw/HeaderItem.java#L227-L239

or if you prefer maybe add these instead:
- mapArtVersionToDexVersion
- mapDexVersionToMaxArtVersion

btw, thanks so much for all the recent changes! please do remember to output a new beta when you are ready so i can update my code without using a local fork.

thanks again!

**Comment by JesusFreke** [comment]
For the oat versions, the intermediate versions really shouldn't be seen much in practice, although it's not impossible, of course. The "minimum" version is chosen because that's the oat version that that version of Android ships with by default. E.g. if you check out that version of Android from AOSP, that's the oat version that will be used.

**Comment by Lanchon** [comment]
ok, thanks! so the dex version maps are an issue of the client or are you planning to add them to dexlib2?

**Comment by JesusFreke** [comment]
I don't have any specific changes in mind at this time, but I may certainly refactor how the various dimensions of api level/dex version/odex version/oat version are mapped to a set of opcodes in the future.
