### ISSUE TITLE
[Q] Info about api level

### ISSUE THREAD

**Issue by ale5000-git** [JesusFreke/smali#466]
Hi,
currently I don't pass the api level, I would like to know if it can cause problems and if possible I would like to know in what cases it make a difference.

**Comment by JesusFreke** [comment]
For normal disassembly (not deodexing, or other cases requiring use of, e.g. MethodAnalyzer), the api level isn't too critical. Especially for "well-formed" dex files that aren't trying to do anything shady

The "official", public opcodes haven't changed since android was first released, except for 1 recent change, although I don't recall if those new opcodes were added for N, or if they're going to be in the next release.

However, dalvik (and possibly art) do allow dex files to use a subset of the non-public/non-official optimized opcodes that are intended mostly for use in odex/oat files. These opcodes have changed in the past, and so the exact instruction that an opcode refers to can change depending on the api level.

The general approach I've taken with smali/baksmali is to provide a reasonable default api level that should work in most cases, and allow the user to override the api level for cases where it doesn't work

**Comment by ale5000-git** [comment]
So, if I have understood correctly if I use a low api level on new ROMs it will not cause any problems instead if I use a high api level on old ROMs it may break, is it like this?

I'm asking because I have a generic detection on Android version, so if if use the lowest possible api for the range that I detect should it work correctly?
Example:
Android 6 - 7 => 23
Android 5 => 21
Android 4.1- 4.4 => 16
Android 2.3 - 4.0 => 9

Also I have read that you implement a workaround for a bug in Dalvik that was fixed in Android 4.2 that is activated only when a low api level is set.
Can I have more info?

**Comment by JesusFreke** [comment]
I don't have a segregation of the optimized opcodes into api ranges offhand. You can find the first/last api level restrictions per opcode in Opcode.java.

If a dex file uses an optimized opcode from a certain api level, but you pass an incompatible api level, the dex file could disassembled incorrectly, resulting in either a failure to reassemble or a verification error at runtime or install time.

I think you're talking about the undocumented "preverified" flag that could be added to a class to prevent dalvik from verifying that class, which gives obfuscators free-reign to do any number of crazy things.

This flag was only intended for use in an odex file, and I implemented a change to enforce that the flag isn't set in a dex file. However, this has nothing to do with the api level that you pass to baksmali/smali/dexlib2. This was something I submitted a patch to dalvik itself for.

**Comment by ale5000-git** [comment]
I'm not very expert about this but I only need to disassemble and reassemble framework.jar, in this case does it make any different specifying or not the api level?

For the bug I'm referring to this:
> One such case is in smali's DexWriter class which implements a workaround for a bug in Dalvik that was fixed in Android 4.2 (https://code.google.com/p/android/issues/detail?id=35304) that causes apps that call the Method.getParameterAnnotations api to crash in some cases (see bug report for more details). The workaround that smali implements is only triggered if the minimum api level is below 17 (Android 4.2)

**Comment by JesusFreke** [comment]
Oh, I dunno. I don't think I remember that. lol! :)

I wouldn't expect a framework.jar to be using any of the optimized opcodes, so it shouldn't matter too much -- unless you're deodexing :). If you are deodexing, then yes, you need to specify the correct api level for the device that the framework.jar is from.

**Comment by ale5000-git** [comment]
Thanks for the help :)
I guess I have to flash a very old Android version and test it to be 100% sure it works correctly without passing api level (currently I don't need deodexing I will create a separate script for that).

If you are curious I'm working on [this](https://github.com/ale5000-git/tingle).
I support almost all Android versions but testing on all supported versions is impossible.

**Comment by JesusFreke** [comment]
I just love seeing projects that compromise the security of the device by bypassing signature checks :p

**Comment by ale5000-git** [comment]
The main point is to patch a compiled ROM in a generic way that works on all possible variation of ROMs, if a ROM include the support built-in it can do it in a more secure way.
Signature spoofing allow to use microG and so avoid GApps, GApps are closed sources so in theory they can do worst things; in particular Play Services can grant itself higher permissions.

I'm looking for a more secure patch, generic enough to work everywhere but I don't think it will be easy (if possible at all).

**Comment by Lanchon** [comment]
@JesusFreke,

signature spoofing does not compromise security of a device in any way. exactly like root does not either.

(and for those that say root does compromise security, i'll refer them to the millions of PCs with linux un*x or windows installations, all of which have admins with root privileges, and i'll ask them to please take control of them since they are compromised. and i'll also point you all to the fact that non-root androids do not exist at all: someone HAS root on all devices! only it is not the owner, it is google and the manufacturer, which is insulting to say the least.)

sig spoofing, root, etc are powerful tools, both with very good reasons to exist, and both with potential for misuse. i certainly wouldn't use a phone without either of those features.

that said, sig spoofing as implemented by microG and omnirom is very restrictive and has very little potential for misuse. the spoofed signatures are never seen by the OS, so all those scenarios you can nightmares about concerning upgrading apps with fakes and stealing their data are not enabled by currently implemented sig spoofing. only local attestation by the OS to 3rd party apps is spoofed, enabling -for instance- the replacement of google play services with free or shim alternatives (which incidentally results in a more secure and trustworthy device, and not the other way around).
