### ISSUE TITLE
[FEATURE REQUEST] Allow baksmali to add comments for registers with known name and/or content

### ISSUE THREAD

**Issue by S-trace** [JesusFreke/smali#509]
Hello.
Thank you for your work!
It would be great if baksmali could mark registers with known meaning and content, using context which is known for it, like this:
```
.method synteticExample(ILjava/lang/String;)V
    .param p1, "flag" # I
    .param p2, "message" # Ljava/lang/String;
    .locals 2

    if-eqz p1, :cond_0 # v1=flag(UNKNOWN):I

    const-string v0, "TAG"
    .local v0, "log_tag":Ljava/lang/String;

    # v0=log_tag("TAG"):Ljava/lang/String; p2=message(UNKNOWN):Ljava/lang/String;
    invoke-static {v0, p2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .end local v0 # "log_tag":Ljava/lang/String;

    const/4 v0, 0x1
    if-eqz v0, :cond_0 # v0=(0x1):I

    const-string v0, "another tag"

    # v0=("another tag"):Ljava/lang/String; p2=message(UNKNOWN):Ljava/lang/String;
    invoke-static {v0, p2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I 

    :cond_0
    return-void
.end method
```
Is it possible to add this feature to baksmali?
It is not very useful for tiny methods, but is absolutely necessary for huge methods with tenth of registers and hundreds lines of the code.
Using regular expressions is not too handy because text editor can't know registers context.

Thank you.

**Comment by JesusFreke** [comment]
So, the problem of course is that actual code is rarely as simple as the example you provided. This would involve basically writing an entire static analyzer. baksmali is already doing a bit of static analysis in order to determine the types of registers, because it's required for deodexing. But actually tracking the values, etc. would be a whole different beast.
