### ISSUE TITLE
Calculating Class Contribution to Dex Size

### ISSUE THREAD

**Issue by Leland-Takamine** [JesusFreke/smali#526]
I'm trying to calculate the contribution of each class to the dex file size. I see that `DexBackedClassDef.getSize()` gives me the "private size of a class definition". The sum of the private sizes of all `DexBackedClassDefs` is less than the dex file size I'm assuming due to data shared between classes that are left out of the class' private size. The following gets me within ~2% of the actual dex file size:

```java
int getCalculatedSize(DexBackedDexFile dexFile) {
    int calculatedSize = 0;
    for (DexBackedClassDef classDef : dexFile.getClasses()) {
        calculatedSize += classDef.getSize();
    }
    for (DexBackedStringReference stringReference : dexFile.getStrings()) {
        calculatedSize += stringReference.getSize();
    }
    for (DexBackedTypeReference typeReference : dexFile.getTypes()) {
        calculatedSize += typeReference.getSize();
    }
    return calculatedSize;
}
```

If this is a valid breakdown of dex file size, then where does the ~2% error come from? Is there a better way to break down the dex file size?

**Comment by JesusFreke** [comment]
there are also method references, field references, method prototype references. and that's just in the indexed sections.

I don't recall offhand exactly what is included in the "class private" size, but things like type list items, some of the annotation related items, the encoded array items can all be shared between classes.

If you want to be rigorous about it, I think you would want to iterate over ever "item" in the dex file, and track it back to the class that uses it. And for items that are referenced by multiple classes, you could split up that item's size equally between all classes that reference it.

**Comment by Leland-Takamine** [comment]
Thanks @JesusFreke - I'll try that out.

**Comment by Leland-Takamine** [comment]
I was able to create a reference graph and item->size mapping based on the DexAnnotator logic. Thanks for the tips!

**Comment by Lanchon** [comment]
the problem is that "class contribution to dex size" is an ill-defined concept based on an incorrect intuition (that such a number exists and is instrinsic to the class), so you cannot calculate it. the dex format avoids redundancy by using references and by that token it effectively is a lossless compression format. and it is also the smallest unit of serialization. so "raw" conceptual/model elements such as classes don't have intrinsic size property to speak of, only full dex files have size.

valid questions you can ask -the usefulness of which i am not implying- are:
- what is the size change of a specific dex if i add or remove this set of items?
- what is the maximum size increase any dex would suffer if i add this set of items to it?

**Comment by hailuo966** [comment]
can I use baksmali.jar to calculate the contribution of each class to the dex file size? Or how can I calculate the contribution of each class to the dex file size? Thanks a lot.
