### ISSUE TITLE
can dexlib2 support oem app?

### ISSUE THREAD

**Issue by popoaichuiniu** [JesusFreke/smali#675]
when we use apktool to analyse oem app, we need manually add framwork. So how dexlib2 solve it?

[apktool analyse oem app](https://github.com/iBotPeaches/Apktool/issues/1359)

**Comment by JesusFreke** [comment]
apktool requires the framework from the device in order to disassembly the apk resources. baksmali doesn't do anything with resources, and doesn't need anything extra for a normal disassembly.

If you're wanting to do register type analysis or deodex an oat/odex file, baksmali does need the device framework, so it has all of the framework classes available for type analysis.
