### ISSUE TITLE
goto/16 what does it mean?

### ISSUE THREAD

**Issue by lebanggit** [JesusFreke/smali#699]
I have disassemble an dex and get this line:

`goto/16 :goto_135`

and some lines:

`goto :goto_135`

What's the diffrents **goto/16** vs **goto**.

**Comment by JesusFreke** [comment]
If you take a look at https://source.android.com/devices/tech/dalvik/dalvik-bytecode, you'll notice that goto/16 accepts a 16-bit jump offset, while goto only accepts an 8-bit jump offset. Small jumps are much more common than longer jumps, so having a separate short vs long instruction allows more efficient use of space, since the short jumps can be encoded with fewer bytes.

**Comment by Lanchon** [comment]
1. does smali always require the `goto/16` and `goto/32` explicitly sized mnemonics? or does it size instructions automatically and only requires explicitly sized mnemonics when you want to force a wider instruction than strictly necessary?

2. and in case it supports automatic sizing: is a `goto/8` also accepted?

**Comment by JesusFreke** [comment]
I was trying to remember that myself, tbh :). I'm 93.27% sure that smali will "upsize" a goto if needed. It won't downside one.

smali follows the official instruction names at https://source.android.com/devices/tech/dalvik/dalvik-bytecode, which does not have a goto/8 :)

**Comment by Lanchon** [comment]
what a strange coincidence, 93.27% is also the fraction of percentages made up on the spot.

**Comment by 404-not-find** [comment]
Yes ,it has only goto +AA in  https://source.android.com/devices/tech/dalvik/dalvik-bytecode, which does not have a goto/8, no goto/8 which goto/8 is default for goto. I want to know if I used goto where should use goto/16, what will happened. Thanks.
