### ISSUE TITLE
关于smali多dex分包

### ISSUE THREAD

**Issue by gittanker** [JesusFreke/smali#750]
多dex反编译smali代码合并之后重新分包，超过65535方法，请问如何才能正确分包区分主从classes.dex，classes2.dex …等待您的解答

**Comment by JesusFreke** [comment]
Moving classes between dex files generally requires deeper knowledge of the apk than smali has. Your best bet is manually find and move some classes that are safe to move to a secondary dex file

**Comment by gittanker** [comment]
> Moving classes between dex files generally requires deeper knowledge of the apk than smali has. Your best bet is manually find and move some classes that are safe to move to a secondary dex file

谢谢你的回答。自动化是我期望的。我在想办法解决他🍻

**Comment by JesusFreke** [comment]
I don't know the details around exactly which classes are safe to move out of the primary dex file. If I were trying to automate this, my first step would be to try to find the logic that the android toolchain uses to make that decision.

**Comment by Lanchon** [comment]
increase the minsdk to android 5. in ART (android 5+) all dex files are the same and there is nothing special about the 'main' dex anymore (you loose compatibility with android 4.x of course). then shuffle classes among dex files any way you want so that they don't overflow.

otherwise use dexpatcher-tool command line to add classes: it does this automatically.
