### ISSUE TITLE
[question] "ClassFileNameHandler.makePhysicalName(int suffix)"

### ISSUE THREAD

**Issue by warren-bank** [JesusFreke/smali#770]
Hi. First off, your work is brilliant and I appreciate it!

I'm writing a little nodejs utility to remap smali filenames that contain unicode to ascii. I'm about one day in and very nearly done. I hit one minor stumble and wanted to ask a low-level question. It should be easy..

stumble:
* a smali file refers to a class descriptor `Lfoo/bar;`
* the file `smali/foo/bar.smali` doesn't exist
* the file `smali/foo/bar.1.smali` does exist

tracing where this filename came from:
* in apktool, [Baksmali.disassembleDexFile()](https://github.com/iBotPeaches/Apktool/blob/b4493a51bbc5582175e1f6a93a71ae7c58428818/brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliDecoder.java#L101)
* in Baksmali, [File smaliFile = fileNameHandler.getUniqueFilenameForClass(classDescriptor)](https://github.com/JesusFreke/smali/blob/239b64ba003accffd1b0cf7c1c58d35435f5e94a/baksmali/src/main/java/org/jf/baksmali/Baksmali.java#L121)
* in ClassFileNameHandler:
  - [public File getUniqueFilenameForClass(String className)](https://github.com/JesusFreke/smali/blob/239b64ba003accffd1b0cf7c1c58d35435f5e94a/util/src/main/java/org/jf/util/ClassFileNameHandler.java#L87)
  - [protected String makePhysicalName(int suffix)](https://github.com/JesusFreke/smali/blob/239b64ba003accffd1b0cf7c1c58d35435f5e94a/util/src/main/java/org/jf/util/ClassFileNameHandler.java#L430)
    * `return addSuffixBeforeExtension(getNormalizedName(true), '.' + Integer.toString(suffix))`
  - [private static String addSuffixBeforeExtension(String pathElement, String suffix)](https://github.com/JesusFreke/smali/blob/239b64ba003accffd1b0cf7c1c58d35435f5e94a/util/src/main/java/org/jf/util/ClassFileNameHandler.java#L438)

anecdotal observations:
* the trailing numeric suffix can be any number (ie: not just 1)
* it doesn't correspond to any sequence of similarly named files

questions:
* what is `suffix`, and how is it being used in `protected String makePhysicalName(int suffix)`?
* well.. more to the point:
  - would it be safe to _always_ assume that a filename  `smali/foo/bar(\.[\d]+)?.smali` maps to the class descriptor `Lfoo/bar;`, or would such an assumption lead to namespace collision?

**Comment by JesusFreke** [comment]
It's been a while since I wrote/looked at/thought about that logic, so grab a few grains of salt :)

As far as I can remember, any period before the one for the extension will be one added by that logic you mention, to handle collisions.

The most common way to run into this is to have something like a La; and LA; class, on a case-insensitive filesystem.

You *might* be able to figure out the exact class from the actual case of the filename. Even though a.smali and A.smali refer to the same file, I think the correct case should usually be kept as-written. So you might be able to assume that A.smali (or A.123.smali) refers to LA; instead of La;. But I'm not 100% sure about that. There may be some edge cases where the case of the filename isn't kept.

And if you read the javadoc of that class you mentioned, there are other cases where parts of the filename may be removed and replaced with a #, due to filename length restrictions, which would certainly complicate trying to infer the class name from the file name :)

Your best bet would be to look for the .class statement in the smali file. For smali files generated by baksmali, the .class file should always be the first line, afair. Although technically it could occur elsewhere in the file.

**Comment by warren-bank** [comment]
thanks for the rapid and informative response..

I like your suggestion about using the `.class` statement; it side-steps the entire issue.

you're a rockstar!

**Comment by warren-bank** [comment]
thanks again, that new methodology worked first try; I was finally able to rebuild a fully-functional apk that I otherwise couldn't.

I published the tool to [github](https://github.com/warren-bank/node-remap-apktool-unicode-filenames) and [npm](https://www.npmjs.com/package/@warren-bank/node-remap-apktool-unicode-filenames) for anyone who may find it useful.
