### ISSUE TITLE
Ive been Hacked please help me

### ISSUE THREAD

**Issue by Jcutty8** [JesusFreke/smali#866]
Someone has hacked me and I need assistance removing your software. Could you please message me back as soon as possible regarding this matter

**Comment by developer-krushna** [comment]
What 🤯

**Comment by Jcutty87** [comment]
Do i need a lap top for this  to be removed off my phone?! Like I'm super pissed that ppl do this... I had a hoe sleepin next to me and believe she connected my phone to a laptop  and put administrator and coded all my applications

**Comment by Lanchon** [comment]
you must be a very bad lay

**Comment by Jcutty8** [comment]
Bahaha no she still fuckin me but no bro can help me man🤣😂😁she's just a thief bucket stealing my data lol now can u seriously help like instructions .. i dont have a computer  so  if u can instruct me I'll do it on laptop


Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by Lanchon** [comment]
you can sometimes remove smali from a phone with an angle grinder.

seriously, no one here can help you because smali is not software for hacking phones. if your phone is misbehaving, your last resort is doing a full reset (sometimes called factory reset), but you'll loose all the data in your phone that is not backed up in the cloud. make sure you know username and password to all your accounts and apps, **especially google (android) or apple (iphone) account**, and that you can receive texts on phone numbers you gave to the services you want to keep. **do not proceed** without this info.

you can close this issue now, nobody here can help you. good luck,

**Comment by Stargazerr1** [comment]
> Bahaha no she still fuckin me but no bro can help me man🤣😂😁she's just a thief bucket stealing my data lol now can u seriously help like instructions .. i dont have a computer so if u can instruct me I'll do it on laptop Sent from my Bell Samsung device over Canada’s largest network.
> […](#)

Message Blackhathacker110 on telegram he helped me hacked my girlfriends Snapchat when she was cheating on me,he can hack everything else Instagram Facebook gmail and so on,https://t.me/Blackhathacker110

**Comment by Jcutty8** [comment]
All I'm asking is how do I put original software back on phone and original apps back on phone? I think  they hacked emails but I also think they actually coded all my apps n shit .. I look at the licenses and shit they come from here some of them.. also feel like someone's watching me through cam..  I think and sense that my apps are manipulated and coded.. I just wanna know how to correct it and put on original software and w.e else they can mess with.. what's most common things they could have done to phone..
